-- Membership self-cancellation support
-- Run once in Supabase SQL Editor before testing the cancel-membership button.

alter table public.members
  add column if not exists membership_status text not null default 'active',
  add column if not exists membership_cancelled_at timestamptz;

create table if not exists public.membership_cancellations (
  id bigint generated by default as identity primary key,
  member_id text not null,
  reason text not null check (
    reason in (
      'not_using',
      'no_news',
      'duplicate_account',
      'use_another_account',
      'privacy',
      'other'
    )
  ),
  reason_detail text,
  cancelled_at timestamptz not null default now()
);

create index if not exists membership_cancellations_member_id_idx
  on public.membership_cancellations (member_id);

create index if not exists members_membership_status_idx
  on public.members (membership_status);

alter table public.membership_cancellations enable row level security;

-- Browser clients do not write this table directly.
-- The existing server API uses SUPABASE_SECRET_KEY / service role.
