-- Nathoeng Connect Phase 2
-- Run once in Supabase SQL Editor before enabling Web Push in production.

create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  member_id text not null,
  endpoint text not null unique,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists push_subscriptions_member_id_idx
  on public.push_subscriptions (member_id);

create index if not exists push_subscriptions_active_idx
  on public.push_subscriptions (is_active);

alter table public.push_subscriptions enable row level security;

-- Browser clients never access this table directly.
-- The existing /api/practice-messages server route uses the Supabase secret key.
